spring: 
    profiles: 
        active: dev
        
---
spring: 
    profiles: dev
    application: 
        name: springclooud-config-dev
---
spring: 
    profiles: test
    application: 
        name: springclooud-config-test