spring:
    profiles:
        active: dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: spring-eureka-server

eureka:
  instance:
    hostname: node1
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://node2:7002/eureka

---
server:
  port: 7003
 spring:
  profiles: test
  application:
    name: spring-eureka-server

eureka:
  instance:
    hostname: node1
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://node2:7002/eureka
